# Generated by Django 4.0.4 on 2022-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
