# Generated by Django 4.0.4 on 2022-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
