# Generated by Django 4.0.4 on 2022-05-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_publishers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='average_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.publishers'),
        ),
        migrations.AddField(
            model_name='books',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='text_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_bn',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_bn_13',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
