# Generated by Django 4.0.4 on 2022-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
