# Generated by Django 4.0.4 on 2022-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_books_average_rating_books_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
