# Generated by Django 4.0.4 on 2022-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_bn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_bn_13',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
