# Generated by Django 4.0.4 on 2022-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_books_is_bn_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_bn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_bn_13',
            field=models.CharField(max_length=13),
        ),
    ]
